@startuml
'https://plantuml.com/sequence-diagram

autonumber

title 捕获流程时序图 
actor 用户 as User
entity 设备列表视图 as DeviceView
entity 设备列表模型 as DeviceModel
entity 捕获列表模型 as CaptureModel
entity 捕获列表视图 as CaptureView

User --> DeviceView: 用户选择设备
DeviceView --> DeviceModel: 启动捕获
DeviceModel --> CaptureModel: 接收数据包
CaptureModel --> CaptureView: 添加列表
CaptureView --> User: 返回捕获列表

@enduml