@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户 as User
entity 捕获列表视图 as CaptureView
entity 捕获列表模型 as CaptureModel
entity 实体展示模型 as InfoModel
entity 实体展示视图 as InfoView

User --> CaptureView: 选择一个数据包
CaptureView --> CaptureModel: 选择数据包对象
CaptureModel --> InfoModel: 发送展示消息
InfoModel --> InfoView: 添加实体信息对象
InfoView --> User: 返回实体信息


@enduml