@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户 as User
entity 设备列表视图 as DeviceView
entity 设备列表模型 as DeviceModel
entity 实体展示模型 as InfoModel
entity 实体展示视图 as InfoView

User --> DeviceView: 选择一个设备
DeviceView --> DeviceModel: 选择设备对象
DeviceModel --> InfoModel: 发送展示消息
InfoModel --> InfoView: 添加实体信息对象
InfoView --> User: 返回实体信息

@enduml