@startuml
'https://plantuml.com/use-case-diagram

skinparam dpi 450
left to right direction

actor 用户 as User

package ICMPv6协议分析系统 {
    
    package 设备管理模块 {
        usecase 查看设备列表
        usecase 获取设备列表
    }
    
    package 捕获管理模块 {
        usecase 数据包捕获
        usecase 查看捕获列表
        usecase 读取数据包文件
        usecase 保存数据包文件
    }
    
    package 实体展示模块 {
        usecase 查看设备详细信息
        usecase 查看数据包
        usecase 数据包解析
    }
}

User --> 查看设备列表
User --> 数据包捕获
查看设备列表 ..> 获取设备列表: <include>

User --> 查看捕获列表
User --> 读取数据包文件
User --> 保存数据包文件
查看数据包 ..> 数据包解析 :<include>

User --> 查看设备详细信息
User --> 查看数据包

@enduml