@startuml
'https://plantuml.com/component-diagram

skinparam dpi 300

package View {
    component DeviceListPanel
    component CaptureListPanel
    component InfoPanel
}

package ViewModel {
    component DeviceListViewModel
    component CaptureListViewModel
    component InfoViewModel
}

package Model {
    component NetPacket
    component Repository
}

DeviceListPanel --> DeviceListViewModel
CaptureListPanel --> CaptureListViewModel
InfoPanel --> InfoViewModel

CaptureListViewModel -> DeviceListViewModel
InfoViewModel -> DeviceListViewModel
InfoViewModel -> CaptureListViewModel

InfoViewModel--> NetPacket
InfoViewModel --> Repository
DeviceListViewModel --> Repository


@enduml